import openai
from constants import *


class Chatbot():
    """Class representing a chatbot powered by OpenAI's GPT models."""

    def __init__(self):
        """Initialize the chatbot with the OpenAI API key."""
        openai.api_key = OPENAI_API_KEY

    def get_response(self, user_input, gpt_model=GPT_MODEL, tokens=TOKENS, temperature=TEMPERATURE):
        """
        Get a response from the chatbot for the given user input.

        Args:
            user_input (str): The input text provided by the user.
            gpt_model (str): The GPT model to use for generating the response.
            tokens (int): The maximum number of tokens (words) allowed in the response.
            temperature (float): The temperature parameter controlling the randomness of the response.
                                 Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic.

        Returns:
            str: The response generated by the chatbot.
        """
        try:
            # Make API request to generate chat completion
            response = openai.chat.completions.create(
                model=gpt_model,  # Specify the GPT model to use
                messages=[
                    # System message
                    {"role": "system", "content": "You are a helpful assistant."},
                    {"role": "user", "content": user_input}  # User message
                ],
                max_tokens=tokens,  # Specify the maximum number of tokens allowed in the response
                # Specify the temperature parameter controlling response randomness
                temperature=temperature
            )

            # Extract and return the generated response message
            return response.choices[0].message.content
        except openai.RateLimitError as e:
            # Handle RateLimitError if API request exceeds quota
            return "\n--- Rate limit exceeded. Please try again later or upgrade your plan. ---\n"


if __name__ == '__main__':
    Chatbot = Chatbot()
    response = Chatbot.get_response("write a joke about birds.")
    print(response)
